let data = [
  { emoji: "😀", description: "Grinning Face" },
  { emoji: "😃", description: "Grinning Face with Big Eyes" },
  { emoji: "😄", description: "Grinning Face with Smiling Eyes" },
  { emoji: "😁", description: "Beaming Face with Smiling Eyes" },
  { emoji: "😆", description: "Grinning Squinting Face" },
  { emoji: "😅", description: "Grinning Face with Sweat" },
  { emoji: "🤣", description: "Rolling on the Floor Laughing" },
  { emoji: "😂", description: "Face with Tears of Joy" },
  { emoji: "🙂", description: "Slightly Smiling Face" },
  { emoji: "🙃", description: "Upside-Down Face" },
  { emoji: "😉", description: "Winking Face" },
  { emoji: "😊", description: "Smiling Face with Smiling Eyes" },
  { emoji: "😇", description: "Smiling Face with Halo" },
  { emoji: "🥰", description: "Smiling Face with Hearts" },
  { emoji: "😍", description: "Smiling Face with Heart-Eyes" },
  { emoji: "🤩", description: "Star-Struck" },
  { emoji: "😘", description: "Face Blowing a Kiss" },
  { emoji: "😗", description: "Kissing Face" },
  { emoji: "☺", description: "Smiling Face" },
  { emoji: "😚", description: "Kissing Face with Closed Eyes" },
  { emoji: "😙", description: "Kissing Face with Smiling Eyes" },
  { emoji: "😋", description: "Face Savoring Food" },
  { emoji: "😛", description: "Face with Tongue" },
  { emoji: "😜", description: "Winking Face with Tongue" },
  { emoji: "🤪", description: "Zany Face" },
  { emoji: "😝", description: "Squinting Face with Tongue" },
  { emoji: "🤑", description: "Money-Mouth Face" },
  { emoji: "🤗", description: "Hugging Face" },
  { emoji: "🤭", description: "Face with Hand Over Mouth" },
  { emoji: "🤫", description: "Shushing Face" },
  { emoji: "🤔", description: "Thinking Face" },
  { emoji: "🤐", description: "Zipper-Mouth Face" },
  { emoji: "🤨", description: "Face with Raised Eyebrow" },
  { emoji: "😐", description: "Neutral Face" },
  { emoji: "😑", description: "Expressionless Face" },
  { emoji: "😶", description: "Face Without Mouth" },
  { emoji: "😏", description: "Smirking Face" },
  { emoji: "😒", description: "Unamused Face" },
  { emoji: "🙄", description: "Face with Rolling Eyes" },
  { emoji: "😬", description: "Grimacing Face" },
  { emoji: "🤥", description: "Lying Face" },
  { emoji: "😌", description: "Relieved Face" },
  { emoji: "😔", description: "Pensive Face" },
  { emoji: "😪", description: "Sleepy Face" },
  { emoji: "🤤", description: "Drooling Face" },
  { emoji: "😴", description: "Sleeping Face" },
  { emoji: "😷", description: "Face with Medical Mask" },
  { emoji: "🤒", description: "Face with Thermometer" },
  { emoji: "🤕", description: "Face with Head-Bandage" },
  { emoji: "🤢", description: "Nauseated Face" },
  { emoji: "🤮", description: "Face Vomiting" },
  { emoji: "🤧", description: "Sneezing Face" },
  { emoji: "🥵", description: "Hot Face" },
  { emoji: "🥶", description: "Cold Face" },
  { emoji: "🥴", description: "Woozy Face" },
  { emoji: "😵", description: "Dizzy Face" },
  { emoji: "🤯", description: "Exploding Head" },
  { emoji: "🤠", description: "Cowboy Hat Face" },
  { emoji: "🥳", description: "Partying Face" },
  { emoji: "😎", description: "Smiling Face with Sunglasses" },
  { emoji: "🤓", description: "Nerd Face" },
  { emoji: "🧐", description: "Face with Monocle" },
  { emoji: "😕", description: "Confused Face" },
  { emoji: "😟", description: "Worried Face" },
  { emoji: "🙁", description: "Slightly Frowning Face" },
  { emoji: "☹", description: "Frowning Face" },
  { emoji: "😮", description: "Face with Open Mouth" },
  { emoji: "😯", description: "Hushed Face" },
  { emoji: "😲", description: "Astonished Face" },
  { emoji: "😳", description: "Flushed Face" },
  { emoji: "🥺", description: "Pleading Face" },
  { emoji: "😦", description: "Frowning Face with Open Mouth" },
  { emoji: "😧", description: "Anguished Face" },
  { emoji: "😨", description: "Fearful Face" },
  { emoji: "😰", description: "Anxious Face with Sweat" },
  { emoji: "😥", description: "Sad but Relieved Face" },
  { emoji: "😢", description: "Crying Face" },
  { emoji: "😭", description: "Loudly Crying Face" },
  { emoji: "😱", description: "Face Screaming in Fear" },
  { emoji: "😖", description: "Confounded Face" },
  { emoji: "😣", description: "Persevering Face" },
  { emoji: "😞", description: "Disappointed Face" },
  { emoji: "😓", description: "Downcast Face with Sweat" },
  { emoji: "😩", description: "Weary Face" },
  { emoji: "😫", description: "Tired Face" },
  { emoji: "🥱", description: "Yawning Face" },
  { emoji: "😤", description: "Face with Steam From Nose" },
  { emoji: "😡", description: "Pouting Face" },
  { emoji: "😠", description: "Angry Face" },
  { emoji: "🤬", description: "Face with Symbols on Mouth" },
  { emoji: "😈", description: "Smiling Face with Horns" },
  { emoji: "👿", description: "Angry Face with Horns" },
  { emoji: "💀", description: "Skull" },
  { emoji: "☠", description: "Skull and Crossbones" },
  { emoji: "💩", description: "Pile of Poo" },
  { emoji: "🤡", description: "Clown Face" },
  { emoji: "👹", description: "Ogre" },
  { emoji: "👺", description: "Goblin" },
  { emoji: "👻", description: "Ghost" },
  { emoji: "👽", description: "Alien" },
  { emoji: "👾", description: "Alien Monster" },
  { emoji: "🤖", description: "Robot" },
  { emoji: "😺", description: "Grinning Cat" },
  { emoji: "😸", description: "Grinning Cat with Smiling Eyes" },
  { emoji: "😹", description: "Cat with Tears of Joy" },
  { emoji: "😻", description: "Smiling Cat with Heart-Eyes" },
  { emoji: "😼", description: "Cat with Wry Smile" },
  { emoji: "😽", description: "Kissing Cat" },
  { emoji: "🙀", description: "Weary Cat" },
  { emoji: "😿", description: "Crying Cat" },
  { emoji: "😾", description: "Pouting Cat" },
  { emoji: "💋", description: "Kiss Mark" },
  { emoji: "👋", description: "Waving Hand" },
  { emoji: "🤚", description: "Raised Back of Hand" },
  { emoji: "🖐", description: "Hand with Fingers Splayed" },
  { emoji: "✋", description: "Raised Hand" },
  { emoji: "🖖", description: "Vulcan Salute" },
  { emoji: "👌", description: "OK Hand" },
  { emoji: "🤏", description: "Pinching Hand" },
  { emoji: "✌", description: "Victory Hand" },
  { emoji: "🤞", description: "Crossed Fingers" },
  { emoji: "🤟", description: "Love-You Gesture" },
  { emoji: "🤘", description: "Sign of the Horns" },
  { emoji: "🤙", description: "Call Me Hand" },
  { emoji: "👈", description: "Backhand Index Pointing Left" },
  { emoji: "👉", description: "Backhand Index Pointing Right" },
  { emoji: "👆", description: "Backhand Index Pointing Up" },
  { emoji: "🖕", description: "Middle Finger" },
  { emoji: "👇", description: "Backhand Index Pointing Down" },
  { emoji: "☝", description: "Index Pointing Up" },
  { emoji: "👍", description: "Thumbs Up" },
  { emoji: "👎", description: "Thumbs Down" },
  { emoji: "✊", description: "Raised Fist" },
  { emoji: "👊", description: "Oncoming Fist" },
  { emoji: "🤛", description: "Left-Facing Fist" },
  { emoji: "🤜", description: "Right-Facing Fist" },
  { emoji: "👏", description: "Clapping Hands" },
  { emoji: "🙌", description: "Raising Hands" },
  { emoji: "👐", description: "Open Hands" },
  { emoji: "🤲", description: "Palms Up Together" },
  { emoji: "🤝", description: "Handshake" },
  { emoji: "🙏", description: "Folded Hands" },
  { emoji: "✍", description: "Writing Hand" },
  { emoji: "💅", description: "Nail Polish" },
  { emoji: "🤳", description: "Selfie" },
  { emoji: "💪", description: "Flexed Biceps" },
  { emoji: "🦾", description: "Mechanical Arm" },
  { emoji: "🦿", description: "Mechanical Leg" },
  { emoji: "🦵", description: "Leg" },
  { emoji: "🦶", description: "Foot" },
  { emoji: "👂", description: "Ear" },
  { emoji: "🦻", description: "Ear with Hearing Aid" },
  { emoji: "👃", description: "Nose" },
  { emoji: "🧠", description: "Brain" },
  { emoji: "🦷", description: "Tooth" },
  { emoji: "🦴", description: "Bone" },
  { emoji: "👀", description: "Eyes" },
  { emoji: "👁", description: "Eye" },
  { emoji: "👅", description: "Tongue" },
  { emoji: "👄", description: "Mouth" },
  { emoji: "👶", description: "Baby" },
  { emoji: "🧒", description: "Child" },
  { emoji: "👦", description: "Boy" },
  { emoji: "👧", description: "Girl" },
  { emoji: "🧑", description: "Person" },
  { emoji: "👱", description: "Person: Blond Hair" },
  { emoji: "👨", description: "Man" },
  { emoji: "🧔", description: "Person: Beard" },
  { emoji: "👨‍🦰", description: "Man: Red Hair" },
  { emoji: "👨‍🦱", description: "Man: Curly Hair" },
  { emoji: "👨‍🦳", description: "Man: White Hair" },
  { emoji: "👨‍🦲", description: "Man: Bald" },
  { emoji: "👩", description: "Woman" },
  { emoji: "👩‍🦰", description: "Woman: Red Hair" },
  { emoji: "🧑‍🦰", description: "Person: Red Hair" },
  { emoji: "👩‍🦱", description: "Woman: Curly Hair" },
  { emoji: "🧑‍🦱", description: "Person: Curly Hair" },
  { emoji: "👩‍🦳", description: "Woman: White Hair" },
  { emoji: "🧑‍🦳", description: "Person: White Hair" },
  { emoji: "👩‍🦲", description: "Woman: Bald" },
  { emoji: "🧑‍🦲", description: "Person: Bald" },
  { emoji: "👱‍♀️", description: "Woman: Blond Hair" },
  { emoji: "👱‍♂️", description: "Man: Blond Hair" },
  { emoji: "🧓", description: "Older Person" },
  { emoji: "👴", description: "Old Man" },
  { emoji: "👵", description: "Old Woman" },
  { emoji: "🙍", description: "Person Frowning" },
  { emoji: "🙍‍♂️", description: "Man Frowning" },
  { emoji: "🙍‍♀️", description: "Woman Frowning" },
  { emoji: "🙎", description: "Person Pouting" },
  { emoji: "🙎‍♂️", description: "Man Pouting" },
  { emoji: "🙎‍♀️", description: "Woman Pouting" },
  { emoji: "🙅", description: "Person Gesturing No" },
  { emoji: "🙅‍♂️", description: "Man Gesturing No" },
  { emoji: "🙅‍♀️", description: "Woman Gesturing No" },
  { emoji: "🙆", description: "Person Gesturing OK" },
  { emoji: "🙆‍♂️", description: "Man Gesturing OK" },
  { emoji: "🙆‍♀️", description: "Woman Gesturing OK" },
  { emoji: "💁", description: "Person Tipping Hand" },
  { emoji: "💁‍♂️", description: "Man Tipping Hand" },
  { emoji: "💁‍♀️", description: "Woman Tipping Hand" },
  { emoji: "🙋", description: "Person Raising Hand" },
  { emoji: "🙋‍♂️", description: "Man Raising Hand" },
  { emoji: "🙋‍♀️", description: "Woman Raising Hand" },
  { emoji: "🧏", description: "Deaf Person" },
  { emoji: "🧏‍♂️", description: "Deaf Man" },
  { emoji: "🧏‍♀️", description: "Deaf Woman" },
  { emoji: "🙇", description: "Person Bowing" },
  { emoji: "🙇‍♂️", description: "Man Bowing" },
  { emoji: "🙇‍♀️", description: "Woman Bowing" },
  { emoji: "🤦", description: "Person Facepalming" },
  { emoji: "🤦‍♂️", description: "Man Facepalming" },
  { emoji: "🤦‍♀️", description: "Woman Facepalming" },
  { emoji: "🤷", description: "Person Shrugging" },
  { emoji: "🤷‍♂️", description: "Man Shrugging" },
  { emoji: "🤷‍♀️", description: "Woman Shrugging" },
  { emoji: "🧑‍⚕️", description: "Health Worker" },
  { emoji: "👨‍⚕️", description: "Man Health Worker" },
  { emoji: "👩‍⚕️", description: "Woman Health Worker" },
  { emoji: "🧑‍🎓", description: "Student" },
  { emoji: "👨‍🎓", description: "Man Student" },
  { emoji: "👩‍🎓", description: "Woman Student" },
  { emoji: "🧑‍🏫", description: "Teacher" },
  { emoji: "👨‍🏫", description: "Man Teacher" },
  { emoji: "👩‍🏫", description: "Woman Teacher" },
  { emoji: "🧑‍⚖️", description: "Judge" },
  { emoji: "👨‍⚖️", description: "Man Judge" },
  { emoji: "👩‍⚖️", description: "Woman Judge" },
  { emoji: "🧑‍🌾", description: "Farmer" },
  { emoji: "👨‍🌾", description: "Man Farmer" },
  { emoji: "👩‍🌾", description: "Woman Farmer" },
  { emoji: "🧑‍🍳", description: "Cook" },
  { emoji: "👨‍🍳", description: "Man Cook" },
  { emoji: "👩‍🍳", description: "Woman Cook" },
  { emoji: "🧑‍🔧", description: "Mechanic" },
  { emoji: "👨‍🔧", description: "Man Mechanic" },
  { emoji: "👩‍🔧", description: "Woman Mechanic" },
  { emoji: "🧑‍🏭", description: "Factory Worker" },
  { emoji: "👨‍🏭", description: "Man Factory Worker" },
  { emoji: "👩‍🏭", description: "Woman Factory Worker" },
  { emoji: "🧑‍💼", description: "Office Worker" },
  { emoji: "👨‍💼", description: "Man Office Worker" },
  { emoji: "👩‍💼", description: "Woman Office Worker" },
  { emoji: "🧑‍🔬", description: "Scientist" },
  { emoji: "👨‍🔬", description: "Man Scientist" },
  { emoji: "👩‍🔬", description: "Woman Scientist" },
  { emoji: "🧑‍💻", description: "Technologist" },
  { emoji: "👨‍💻", description: "Man Technologist" },
  { emoji: "👩‍💻", description: "Woman Technologist" },
  { emoji: "🧑‍🎤", description: "Singer" },
  { emoji: "👨‍🎤", description: "Man Singer" },
  { emoji: "👩‍🎤", description: "Woman Singer" },
  { emoji: "🧑‍🎨", description: "Artist" },
  { emoji: "👨‍🎨", description: "Man Artist" },
  { emoji: "👩‍🎨", description: "Woman Artist" },
  { emoji: "🧑‍✈️", description: "Pilot" },
  { emoji: "👨‍✈️", description: "Man Pilot" },
  { emoji: "👩‍✈️", description: "Woman Pilot" },
  { emoji: "🧑‍🚀", description: "Astronaut" },
  { emoji: "👨‍🚀", description: "Man Astronaut" },
  { emoji: "👩‍🚀", description: "Woman Astronaut" },
  { emoji: "🧑‍🚒", description: "Firefighter" },
  { emoji: "👨‍🚒", description: "Man Firefighter" },
  { emoji: "👩‍🚒", description: "Woman Firefighter" },
  { emoji: "👮", description: "Police Officer" },
  { emoji: "👮‍♂️", description: "Man Police Officer" },
  { emoji: "👮‍♀️", description: "Woman Police Officer" },
  { emoji: "🕵", description: "Detective" },
  { emoji: "🕵️‍♂️", description: "Man Detective" },
  { emoji: "🕵️‍♀️", description: "Woman Detective" },
  { emoji: "💂", description: "Guard" },
  { emoji: "💂‍♂️", description: "Man Guard" },
  { emoji: "💂‍♀️", description: "Woman Guard" },
  { emoji: "👷", description: "Construction Worker" },
  { emoji: "👷‍♂️", description: "Man Construction Worker" },
  { emoji: "👷‍♀️", description: "Woman Construction Worker" },
  { emoji: "🤴", description: "Prince" },
  { emoji: "👸", description: "Princess" },
  { emoji: "👳", description: "Person Wearing Turban" },
  { emoji: "👳‍♂️", description: "Man Wearing Turban" },
  { emoji: "👳‍♀️", description: "Woman Wearing Turban" },
  { emoji: "👲", description: "Person With Skullcap" },
  { emoji: "🧕", description: "Woman with Headscarf" },
  { emoji: "🤵", description: "Person in Tuxedo" },
  { emoji: "👰", description: "Person With Veil" },
  { emoji: "🤰", description: "Pregnant Woman" },
  { emoji: "🤱", description: "Breast-Feeding" },
  { emoji: "🧑‍🍼", description: "Person Feeding Baby" },
  { emoji: "👼", description: "Baby Angel" },
  { emoji: "🎅", description: "Santa Claus" },
  { emoji: "🤶", description: "Mrs. Claus" },
  { emoji: "🦸", description: "Superhero" },
  { emoji: "🦸‍♂️", description: "Man Superhero" },
  { emoji: "🦸‍♀️", description: "Woman Superhero" },
  { emoji: "🦹", description: "Supervillain" },
  { emoji: "🦹‍♂️", description: "Man Supervillain" },
  { emoji: "🦹‍♀️", description: "Woman Supervillain" },
  { emoji: "🧙", description: "Mage" },
  { emoji: "🧙‍♂️", description: "Man Mage" },
  { emoji: "🧙‍♀️", description: "Woman Mage" },
  { emoji: "🧚", description: "Fairy" },
  { emoji: "🧚‍♂️", description: "Man Fairy" },
  { emoji: "🧚‍♀️", description: "Woman Fairy" },
  { emoji: "🧛", description: "Vampire" },
  { emoji: "🧛‍♂️", description: "Man Vampire" },
  { emoji: "🧛‍♀️", description: "Woman Vampire" },
  { emoji: "🧜", description: "Merperson" },
  { emoji: "🧜‍♂️", description: "Merman" },
  { emoji: "🧜‍♀️", description: "Mermaid" },
  { emoji: "🧝", description: "Elf" },
  { emoji: "🧝‍♂️", description: "Man Elf" },
  { emoji: "🧝‍♀️", description: "Woman Elf" },
  { emoji: "🧞", description: "Genie" },
  { emoji: "🧞‍♂️", description: "Man Genie" },
  { emoji: "🧞‍♀️", description: "Woman Genie" },
  { emoji: "🧟", description: "Zombie" },
  { emoji: "🧟‍♂️", description: "Man Zombie" },
  { emoji: "🧟‍♀️", description: "Woman Zombie" },
  { emoji: "💆", description: "Person Getting Massage" },
  { emoji: "💆‍♂️", description: "Man Getting Massage" },
  { emoji: "💆‍♀️", description: "Woman Getting Massage" },
  { emoji: "💇", description: "Person Getting Haircut" },
  { emoji: "💇‍♂️", description: "Man Getting Haircut" },
  { emoji: "💇‍♀️", description: "Woman Getting Haircut" },
  { emoji: "🚶", description: "Person Walking" },
  { emoji: "🚶‍♂️", description: "Man Walking" },
  { emoji: "🚶‍♀️", description: "Woman Walking" },
  { emoji: "🧍", description: "Person Standing" },
  { emoji: "🧍‍♂️", description: "Man Standing" },
  { emoji: "🧍‍♀️", description: "Woman Standing" },
  { emoji: "🧎", description: "Person Kneeling" },
  { emoji: "🧎‍♂️", description: "Man Kneeling" },
  { emoji: "🧎‍♀️", description: "Woman Kneeling" },
  { emoji: "🧑‍🦯", description: "Person with White Cane" },
  { emoji: "👨‍🦯", description: "Man with White Cane" },
  { emoji: "👩‍🦯", description: "Woman with White Cane" },
  { emoji: "🧑‍🦼", description: "Person in Motorized Wheelchair" },
  { emoji: "👨‍🦼", description: "Man in Motorized Wheelchair" },
  { emoji: "👩‍🦼", description: "Woman in Motorized Wheelchair" },
  { emoji: "🧑‍🦽", description: "Person in Manual Wheelchair" },
  { emoji: "👨‍🦽", description: "Man in Manual Wheelchair" },
  { emoji: "👩‍🦽", description: "Woman in Manual Wheelchair" },
  { emoji: "🏃", description: "Person Running" },
  { emoji: "🏃‍♂️", description: "Man Running" },
  { emoji: "🏃‍♀️", description: "Woman Running" },
  { emoji: "💃", description: "Woman Dancing" },
  { emoji: "🕺", description: "Man Dancing" },
  { emoji: "🕴", description: "Person in Suit Levitating" },
  { emoji: "👯", description: "People with Bunny Ears" },
  { emoji: "👯‍♂️", description: "Men with Bunny Ears" },
  { emoji: "👯‍♀️", description: "Women with Bunny Ears" },
  { emoji: "🧖", description: "Person in Steamy Room" },
  { emoji: "🧖‍♂️", description: "Man in Steamy Room" },
  { emoji: "🧖‍♀️", description: "Woman in Steamy Room" },
  { emoji: "🧘", description: "Person in Lotus Position" },
  { emoji: "🧑‍🤝‍🧑", description: "People Holding Hands" },
  { emoji: "👭", description: "Women Holding Hands" },
  { emoji: "👫", description: "Woman and Man Holding Hands" },
  { emoji: "👬", description: "Men Holding Hands" },
  { emoji: "💏", description: "Kiss" },
  { emoji: "👩‍❤️‍💋‍👨", description: "Kiss: Woman, Man" },
  { emoji: "👨‍❤️‍💋‍👨", description: "Kiss: Man, Man" },
  { emoji: "👩‍❤️‍💋‍👩", description: "Kiss: Woman, Woman" },
  { emoji: "💑", description: "Couple with Heart" },
  { emoji: "👩‍❤️‍👨", description: "Couple with Heart: Woman, Man" },
  { emoji: "👨‍❤️‍👨", description: "Couple with Heart: Man, Man" },
  { emoji: "👩‍❤️‍👩", description: "Couple with Heart: Woman, Woman" },
  { emoji: "👪", description: "Family" },
  { emoji: "👨‍👩‍👦", description: "Family: Man, Woman, Boy" },
  { emoji: "👨‍👩‍👧", description: "Family: Man, Woman, Girl" },
  { emoji: "👨‍👩‍👧‍👦", description: "Family: Man, Woman, Girl, Boy" },
  { emoji: "👨‍👩‍👦‍👦", description: "Family: Man, Woman, Boy, Boy" },
  { emoji: "👨‍👩‍👧‍👧", description: "Family: Man, Woman, Girl, Girl" },
  { emoji: "👨‍👨‍👦", description: "Family: Man, Man, Boy" },
  { emoji: "👨‍👨‍👧", description: "Family: Man, Man, Girl" },
  { emoji: "👨‍👨‍👧‍👦", description: "Family: Man, Man, Girl, Boy" },
  { emoji: "👨‍👨‍👦‍👦", description: "Family: Man, Man, Boy, Boy" },
  { emoji: "👨‍👨‍👧‍👧", description: "Family: Man, Man, Girl, Girl" },
  { emoji: "👩‍👩‍👦", description: "Family: Woman, Woman, Boy" },
  { emoji: "👩‍👩‍👧", description: "Family: Woman, Woman, Girl" },
  { emoji: "👩‍👩‍👧‍👦", description: "Family: Woman, Woman, Girl, Boy" },
  { emoji: "👩‍👩‍👦‍👦", description: "Family: Woman, Woman, Boy, Boy" },
  { emoji: "👩‍👩‍👧‍👧", description: "Family: Woman, Woman, Girl, Girl" },
  { emoji: "👨‍👦", description: "Family: Man, Boy" },
  { emoji: "👨‍👦‍👦", description: "Family: Man, Boy, Boy" },
  { emoji: "👨‍👧", description: "Family: Man, Girl" },
  { emoji: "👨‍👧‍👦", description: "Family: Man, Girl, Boy" },
  { emoji: "👨‍👧‍👧", description: "Family: Man, Girl, Girl" },
  { emoji: "👩‍👦", description: "Family: Woman, Boy" },
  { emoji: "👩‍👦‍👦", description: "Family: Woman, Boy, Boy" },
  { emoji: "👩‍👧", description: "Family: Woman, Girl" },
  { emoji: "👩‍👧‍👦", description: "Family: Woman, Girl, Boy" },
  { emoji: "👩‍👧‍👧", description: "Family: Woman, Girl, Girl" },
  { emoji: "🗣", description: "Speaking Head" },
  { emoji: "👤", description: "Bust in Silhouette" },
  { emoji: "👥", description: "Busts in Silhouette" },
  { emoji: "👣", description: "Footprints" },
  { emoji: "🧳", description: "Luggage" },
  { emoji: "🌂", description: "Closed Umbrella" },
  { emoji: "☂", description: "Umbrella" },
  { emoji: "🎃", description: "Jack-O-Lantern" },
  { emoji: "🧵", description: "Thread" },
  { emoji: "🧶", description: "Yarn" },
  { emoji: "👓", description: "Glasses" },
  { emoji: "🕶", description: "Sunglasses" },
  { emoji: "🥽", description: "Goggles" },
  { emoji: "🥼", description: "Lab Coat" },
  { emoji: "🦺", description: "Safety Vest" },
  { emoji: "👔", description: "Necktie" },
  { emoji: "👕", description: "T-Shirt" },
  { emoji: "👖", description: "Jeans" },
  { emoji: "🧣", description: "Scarf" },
  { emoji: "🧤", description: "Gloves" },
  { emoji: "🧥", description: "Coat" },
  { emoji: "🧦", description: "Socks" },
  { emoji: "👗", description: "Dress" },
  { emoji: "👘", description: "Kimono" },
  { emoji: "🥻", description: "Sari" },
  { emoji: "🩱", description: "One-Piece Swimsuit" },
  { emoji: "🩲", description: "Briefs" },
  { emoji: "🩳", description: "Shorts" },
  { emoji: "👙", description: "Bikini" },
  { emoji: "👚", description: "Woman’s Clothes" },
  { emoji: "👛", description: "Purse" },
  { emoji: "👜", description: "Handbag" },
  { emoji: "👝", description: "Clutch Bag" },
  { emoji: "🎒", description: "Backpack" },
  { emoji: "👞", description: "Man’s Shoe" },
  { emoji: "👟", description: "Running Shoe" },
  { emoji: "🥾", description: "Hiking Boot" },
  { emoji: "🥿", description: "Flat Shoe" },
  { emoji: "👠", description: "High-Heeled Shoe" },
  { emoji: "👡", description: "Woman’s Sandal" },
  { emoji: "🩰", description: "Ballet Shoes" },
  { emoji: "👢", description: "Woman’s Boot" },
  { emoji: "👑", description: "Crown" },
  { emoji: "👒", description: "Woman’s Hat" },
  { emoji: "🎩", description: "Top Hat" },
  { emoji: "🎓", description: "Graduation Cap" },
  { emoji: "🧢", description: "Billed Cap" },
  { emoji: "⛑", description: "Rescue Worker’s Helmet" },
  { emoji: "💄", description: "Lipstick" },
  { emoji: "💍", description: "Ring" },
  { emoji: "💼", description: "Briefcase" },
  { emoji: "🩸", description: "Drop of Blood" },
];

export default data;
